Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blogs.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Page for index view
    path('', views.index, name='index'),
    # Page view all the blog post
    path('view_all/', views.view_all, name='view_all'),
    # Page view to edit blog post
    path('edit_blog/<int:blog_id>', views.edit_blog, name='edit_blog'),
    # Page view specific post
    path('view_post/<int:blog_id>', views.view_post, name='view_post'),
    # Page view add a new post
    path('new_post/', views.new_post, name='new_post'),
    # Page view all title
    path('titleView', views.titleView, name='titleView')
]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register')
]

blogs/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    #class Meta:
    #    verbose_name_plural = 'blogpost'

    def __str__(self):
        if len(self.text) >= 50:
            text_ = f"{self.text[:50]}..."
            return text_

        return self.text
    
#class TopicBlog(models.Model):
#    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
#    title = models.CharField(max_length=200)

#    def __str__(self):
#        return self.title


    

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from .models import BlogPost

class Editform(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'text': 'Description'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

blogs/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost
from .forms import Editform

# Create your views here.

def index(request):
    """The index view"""
    return render(request, 'blogs/index.html')

@login_required
def view_all(request):
    """View all blog post"""
    blogpost = BlogPost.objects.filter(owner=request.user).order_by('-date_added')

    content = {'blog_post': blogpost}
    return render(request, 'blogs/view_all.html', content)

@login_required
def edit_blog(request, blog_id):
    """View to edit blog post"""
    edit = BlogPost.objects.get(id=blog_id)

    # Check for the user
    check_blog_owner(edit, request)

    if request.method != 'POST':
        form = Editform(instance=edit)
    else:
        # Post data submitted
        form = Editform(instance=edit, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:view_all')
    
    context = {'title': edit.title, 'text': edit.text,
               'blog_id': edit.id , 'form': form}
    return render(request, 'blogs/edit_blog.html', context)

@login_required
def view_post(reuquest, blog_id):
    """View a specific post"""
    blogpost = BlogPost.objects.get(id=blog_id)

    # Check for the user
    check_blog_owner(blogpost, reuquest)

    content = {'title': blogpost.title, 'text': blogpost.text, 
               'date_': blogpost.date_added}
    return render(reuquest, 'blogs/view_post.html', content)

@login_required
def new_post(request):
    """Add new post"""
    if request.method != 'POST':
        # Create  blank form
        form = Editform()
    else:
        # Post data submitted.
        form = Editform(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:view_all')

    # Display a blank form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def titleView(request):
    posts = BlogPost.objects.filter(owner=request.user).order_by('date_added')

    context = {'posts': posts}
    return render(request,'blogs/titleView.html', context)

def check_blog_owner(blog, request):
    if blog.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process complete form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('blogs:index')
        
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Blog Sample</title>
    </head>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    <!--Alternative file static-->
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
        <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'logout_form.css' %}">

    <body>
        
        <nav class="navbar navbar-expand-mb navbar-light bg-light mb-4 border">
            <a class="navbar-brand" href="{% url 'blogs:index' %}">Home</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-item" href="{% url 'blogs:new_post' %}">Add New Post</a>
                    </li>
                    <li>
                        <a class="nav-item" href="{% url 'blogs:titleView' %}">View Titles</a>
                    </li>
                    <li>
                        <a class="nav-item" href="{% url 'blogs:view_all' %}">View All Post</a>
                    </li>
                </ul>


                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text"}">Hello {{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <form id="logout-form" action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="nav-link" id="logout-button" type="submit">Log Out</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>

        <main role="main" class="container">
            <div class="pb-2 mb-2 border-botton">
                {% block page_header %}{% endblock page_header %}
            </div>
            <div>
                {% block content %}{% endblock content %}
            </div>
        </main>

    </body>
</html>

<!--<p>
    <a href="{% url 'blogs:index' %}">Home</a> -
    <a href="{% url 'blogs:new_post' %}">Add new post</a> -
    <a href="{% url 'blogs:titleView' %}">View titles</a> -
    <a href="{% url 'blogs:view_all' %}">View all post</a> - 

    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <form style="display: inline;" action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button style="
                background: none;
                border: none;
                padding: 0;
                color: blue;
                text-decoration: underline;
                cursor: pointer;" name="submit">Log out</button>
                ((<input type="hidden" name="next" value="{% url 'blogs:index' %}">))
        </form>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a> -
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{ blo ck content %}{ endbl  ock content }-->

blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <p>Edit Blog Post</p>
{% endblock page_header %}

{% block content %}


    <form action="{% url 'blogs:edit_blog' blog_id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!--{ form as_p  }-->
         {% buttons %}
            <button name="submit" class="btn btn-primary">Save change</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}
    <p>Hello Blog, welcome to my guys!</p>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>Add New Post</h3>
{% endblock page_header %}

{% block content %}


    <form action="{% url 'blogs:new_post' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <!--{{ form. as_p }-->
        {% buttons %}
            <button name="submit">[Add post]</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/titleView.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h3>Titles</h3>
{% endblock page_header %}

{% block content %}

    <ul>
        {% for post in posts %}
            <div class="card mb-1">
                <a class="" href="{% url 'blogs:view_post' post.id %}">{{ post.title }}</a>
            </div>
        {% empty %}
            <p>No blog post for title have been added yet. Please add new post.</p>
        {% endfor %}
    </ul>

{% endblock content %}

blogs/templates/blogs/view_all.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <p>Blog Post</p>
{% endblock page_header %}

{% block content %}


    <ul>
        {% for blog in blog_post %}
            <div class="card mb-3">
                <h4 class="card-header">
                    {{ blog.title}} <br>
                    {{ blog.date_added|date:'M d, Y H:i' }}
                    <small><a href="{% url 'blogs:edit_blog' blog.id %}">Edit Post</a></small>
                </h4>
                <div class="card-body">
                    {{ blog.text|linebreaks }}
                </div>
            </div>

        {% empty %}
            <p>No Blog Post yet. Please add new post.</p>
        {% endfor %}
    </ul>

    <p>
        <a href="{% url 'blogs:new_post' %}">[Add new post]</a>
    </p>

{% endblock content %}

blogs/templates/blogs/view_post.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h2>View Post</h2>
{% endblock page_header %}

{% block content %}

    <div class="card mb-3">
        <h4 class="card-header">
            {{ title }} <br>
            {{ date_|date:'M d, Y H:i' }}
        </h4>
        <div class="card-body">
            {{ text|linebreaks }}
        </div>
    </div>

{% endblock content %}